# -*- coding: utf-8 -*-
"""Letters_Count.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zW0qKEctn6ik3SYAmmqmBxwcotXzUYkO
"""

# Given Word
word = input("Please enter your sentence : ")
 
# Take an empty dictionary
dictionary = {}
 
# loop through every letters of word
for character in word:
     
    # check for letter is already
    # present in a dictionary or not
     
    # if present then increment count by 1
    if character in dictionary:
        dictionary[character] += 1
     
    # otherwise assign 1 to it
    else:
        dictionary[character] = 1
 
print("Given Sentence:", word)
print("Count of each letters is:")
 
dictionary