# -*- coding: utf-8 -*-
"""not_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17olq0V_XM5GP_dtarb-ouwqxTsablq6i
"""

word = str(input("please enter your word : "))

def not_string(word):
    first_world = word.split()[0]
    if first_world.__contains__('not'):
        return word
    else:
        return 'not'+ " " + word

not_string(word)